apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-ingress
  namespace: web-app
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: gowebapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
               service:
                 name: go-web-service
                 port:
                   number: 8080
